// about
import aboutStyle from "@/styles/About.module.css";
import Navbar from "@/utils/navbar";
import Head from "next/head";

import HtmlIcon from '@mui/icons-material/Html';
import CssIcon from '@mui/icons-material/Css';


export default function About() {
    return (
        <>
        <Head>
            <title>About</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <div className={aboutStyle.about}>
            <div className={aboutStyle.body}>
                <h1>About me</h1>
                <p>Nothing here :)</p>

            </div>
        </div>
        </>
    );
}