// about
import aboutStyle from "@/styles/About.module.css";
import Navbar from "@/utils/navbar";
import Head from "next/head";

import { Noto_Sans } from 'next/font/google';

const font = Noto_Sans({ subsets: ['latin'], weight: '400' });

export default function About() {
    return (
        <>
        <Head>
            <title>About</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <div className={`${aboutStyle.about} ${font.className}`}>
            <div className={aboutStyle.body}>
                <h1>About me</h1>
                <p>Nothing here :)</p>

            </div>
        </div>
        </>
    );
}