import workStyle from "@/styles/Work.module.css";
import Navbar from "@/utils/navbar";

import SchoolIcon from '@mui/icons-material/School';
import VolunteerActivismIcon from '@mui/icons-material/VolunteerActivism';
import Head from "next/head";
import { Noto_Sans } from 'next/font/google';

import description from "@/utils/description";

const font = Noto_Sans({ subsets: ['latin'], weight: '400' });

export default function Work() {
    return (
        <>
        <Head>
            <title>Experience and Education</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <div className={`${workStyle.work} ${font.className}`}>
            <h1 className={workStyle.heading}>Volunteering Experience</h1>
            <ul className={workStyle.flowDesc}>
                <VolunteerActivismIcon className={workStyle.flowIcon} fontSize="large"></VolunteerActivismIcon>
                <li className={workStyle.flowBox}>
                    <div className={workStyle.demo}>
                        <div className={workStyle.header}>
                            <h2>{description.hc.name}</h2>
                            <i>{description.hc.year}</i>
                        </div>
                        { description.hc.desc.map((i, ind) => {
                            return <p key={ind}>{i}</p>;
                        }) }
                    </div>
                </li>

                <li className={workStyle.flowBox}>
                    <div className={workStyle.demo}>
                        <div className={workStyle.header}>
                            <h2>{description.gwoc.name}</h2>
                            <i>{description.gwoc.year}</i>
                        </div>
                        { description.gwoc.desc.map((i, ind) => {
                            return <p key={ind}>{i}</p>;
                        }) }
                    </div>
                </li>
            </ul>

            <br />

            <h1 className={workStyle.heading}>Education</h1>
            <ul className={workStyle.flowDesc}>
                <SchoolIcon className={workStyle.flowIcon} fontSize="large"></SchoolIcon>
                <li className={workStyle.flowBox}>
                    <div className={workStyle.demo}>
                        <div className={workStyle.header}>
                            <h2>{description.college.name}</h2>
                            <i>{description.college.year}</i>
                        </div>            
                        { description.college.desc.map((i, ind) => {
                            return <p key={ind}>{i}</p>;
                        }) }
                    </div>
                </li>

                <li className={workStyle.flowBox}>
                    <div className={workStyle.demo}>
                        <div className={workStyle.header}>
                            <h2>{description.school.name}</h2>
                            <i>{description.school.year}</i>
                        </div>
                        { description.school.desc.map((i, ind) => {
                            return <p key={ind}>{i}</p>;
                        }) }
                    </div>
                </li>
            </ul>
        </div>
        </>
    );
}