import homeStyle from '@/styles/Home.module.css';
import config_particle from '@/utils/setParticle';
import theme from '@/utils/themes';
import social from '@/utils/social';
import Navbar from "@/utils/navbar";

import { ThemeProvider } from "@emotion/react";
import GitHubIcon from '@mui/icons-material/GitHub';
import LogoDevIcon from '@mui/icons-material/LogoDev';
import EmailRoundedIcon from '@mui/icons-material/EmailRounded';
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import TwitterIcon from '@mui/icons-material/Twitter';
import { SvgIcon } from '@mui/material';
import Head from "next/head";

import Particles from "react-tsparticles";
import { loadFull } from "tsparticles";

export default function Home() {
    const particlesInit = async (main) => {
        await loadFull(main);
        return;
      };
    
    const particlesLoaded = (container) => {
        return;
    };
    return (
        <>
            <Head>
                <title>Subhendu Dash</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className={homeStyle.home}>
                <h1 className={homeStyle.mainHeading}>Welcome to my Portfolio!</h1>
                <Particles className={homeStyle.particles} 
                        id="tsparticles" 
                        init={particlesInit} 
                        loaded={particlesLoaded}
                        options={config_particle} />
                
                <ThemeProvider theme={theme}>
                    <a href={social.github}><GitHubIcon className={homeStyle.socIcon} fontSize="large" color="primary" /></a>
                    <a href={social.devto}><LogoDevIcon className={homeStyle.socIcon} fontSize="large" color="primary" /></a>
                    <a exact="true" href={social.email}><EmailRoundedIcon className={homeStyle.socIcon} fontSize="large" color="primary" /></a>
                    <a href={social.linkedin}><LinkedInIcon className={homeStyle.socIcon} fontSize="large" color="primary" /></a>
                    <a href={social.twitter}><TwitterIcon className={homeStyle.socIcon} fontSize="large" color="primary" /></a>
                    <a href={social.stackoverflow}><SvgIcon className={homeStyle.socIcon} fontSize="large" color="primary">
                        <path d="M15 21h-10v-2h10v2zm6-11.665l-1.621-9.335-1.993.346 1.62 9.335 1.994-.346zm-5.964 6.937l-9.746-.975-.186 2.016 9.755.879.177-1.92zm.538-2.587l-9.276-2.608-.526 1.954 9.306 2.5.496-1.846zm1.204-2.413l-8.297-4.864-1.029 1.743 8.298 4.865 1.028-1.744zm1.866-1.467l-5.339-7.829-1.672 1.14 5.339 7.829 1.672-1.14zm-2.644 4.195v8h-12v-8h-2v10h16v-10h-2z" />
                        </SvgIcon></a>
                </ThemeProvider>
            </div>
        </>
    )
}
