import Navbar from "@/utils/navbar";
import { Paper, Box, Card } from "@mui/material";
import Head from "next/head";

import projectStyle from "@/styles/Projects.module.css";
import ProjectTile from "@/utils/projectTile";
import projectDesc from "@/utils/projectDesc";
import hangman from "@/assets/hangman.png";
import pyagenda from "@/assets/pyagenda.png";
import num from "@/assets/numerical-methods.png";
import profile from "@/assets/profile-fetcher.png";

export default function Projects() {
    return (
        <>
            <Head>
                <title>Subhendu Dash</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className={projectStyle.projects}>
                <h1>Projects</h1>
                <p>The projects I have worked on during my college days...</p>
                <div className={projectStyle.rows}>
                    <ProjectTile img={hangman} 
                                title={projectDesc.hangman.title}
                                description={projectDesc.hangman.description}
                                githubLink={projectDesc.hangman.githubLink}
                                visitLink={projectDesc.hangman.link}>
                    </ProjectTile>

                    <ProjectTile img={pyagenda} 
                            title={projectDesc.pyagenda.title}
                            description={projectDesc.pyagenda.description}
                            githubLink={projectDesc.pyagenda.githubLink}
                            visitLink={projectDesc.pyagenda.link}>
                    </ProjectTile>
                </div>
                <div className={projectStyle.rows}>
                    <ProjectTile img={num} 
                                title={projectDesc.numericalMethods.title}
                                description={projectDesc.numericalMethods.description}
                                githubLink={projectDesc.numericalMethods.githubLink}
                                visitLink={projectDesc.numericalMethods.link}>
                    </ProjectTile>

                    <ProjectTile img={profile} 
                                title={projectDesc.profileFetcher.title}
                                description={projectDesc.profileFetcher.description}
                                githubLink={projectDesc.profileFetcher.githubLink}
                                visitLink={projectDesc.profileFetcher.link}>
                    </ProjectTile>
                </div>
            </div>
        </>
    );
}