import Navbar from "@/utils/navbar";
import { Paper, Box, Card } from "@mui/material";
import Head from "next/head";
import { Noto_Sans } from 'next/font/google';

import projectStyle from "@/styles/Projects.module.css";
import ProjectTile from "@/utils/projectTile";
import projectDesc from "@/utils/projectDesc";
import hangman from "@/assets/hangman.png";
import pyagenda from "@/assets/pyagenda.png";
import num from "@/assets/numerical-methods.png";
import profile from "@/assets/profile-fetcher.png";
import gcra from "@/assets/gcra.png";

const font = Noto_Sans({ subsets: ['latin'], weight: '400' });

export default function Projects() {
    return (
        <>
            <Head>
                <title>Subhendu Dash</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className={`${projectStyle.projects} ${font.className}`}>
                <h2>Projects</h2>
                <p>The projects I have worked on during my college days...</p>
                <div className={projectStyle.rows}>
                    <ProjectTile
                                title={projectDesc.calories_API.title}
                                description={projectDesc.calories_API.description}
                                githubLink={projectDesc.calories_API.githubLink}
                                visitLink={projectDesc.calories_API.link}
                                fullDesc={projectDesc.calories_API.extendedDesc}
                                expand={true}>
                    </ProjectTile>

                    <ProjectTile img={gcra}
                                title={projectDesc.gesture_rec.title}
                                description={projectDesc.gesture_rec.description}
                                githubLink={projectDesc.gesture_rec.githubLink}
                                visitLink={projectDesc.gesture_rec.link}
                                fullDesc={projectDesc.gesture_rec.extendedDesc}
                                expand={true}>
                    </ProjectTile>
                </div>
                <div className={projectStyle.rows}>
                    <ProjectTile img={pyagenda} 
                            title={projectDesc.pyagenda.title}
                            description={projectDesc.pyagenda.description}
                            githubLink={projectDesc.pyagenda.githubLink}
                            visitLink={projectDesc.pyagenda.link}
                            fullDesc={projectDesc.pyagenda.extendedDesc}
                            expand={true}>
                    </ProjectTile>

                    <ProjectTile img={num} 
                                title={projectDesc.numericalMethods.title}
                                description={projectDesc.numericalMethods.description}
                                githubLink={projectDesc.numericalMethods.githubLink}
                                visitLink={projectDesc.numericalMethods.link}
                                fullDesc={projectDesc.numericalMethods.extendedDesc}
                                expand={true}>
                    </ProjectTile>
                </div>
                <div className={projectStyle.rows}>
                    <ProjectTile img={hangman} 
                                title={projectDesc.hangman.title}
                                description={projectDesc.hangman.description}
                                githubLink={projectDesc.hangman.githubLink}
                                visitLink={projectDesc.hangman.link}
                                fullDesc={projectDesc.hangman.extendedDesc}
                                expand={false}>
                    </ProjectTile>

                    <ProjectTile img={profile} 
                                title={projectDesc.profileFetcher.title}
                                description={projectDesc.profileFetcher.description}
                                githubLink={projectDesc.profileFetcher.githubLink}
                                visitLink={projectDesc.profileFetcher.link}
                                expand={false}>
                    </ProjectTile>
                </div>
            </div>
        </>
    );
}